## PIPELINE for local use - once paths have been generated by the HPC and seqdats generated locally ##
# stores multispeed analysis plots in separate PLOTS folder in the path_results folder

setwd("~/Documents/Project/CamtrapSimulation/code")

rm(list = ls())
source("CamtrapSimulation.R", echo=TRUE)

require(ggplot2)
require(ggpubr)

# set which speed parameters to analyse
Mb_range <- c(1,5,10,15,20,25,30,35,40,45,50)

# set number of iters for each to analyse
iters <- c(20,20,19,20,20,20,20,20,20,20,20)

Mb_iters <- data.frame(Mb_range = Mb_range, iter = iters)

# additional parameters:
# species = 0 # currently: 0 = small, 1 = large --> ultimately: want: 1 = small herbivores, 2 = large herbivores, 3 = small carnivores, 4 = large carnivores
r = 9
th = 0.7
# twoCTs = FALSE
# connectedCTs = FALSE

# generate plotting variables
generate_plotting_variables(Mb_iters, r=r, th=th)

# make plots
make_plots()