## PIPELINE for local use - once paths have been generated by the HPC and seqdats generated locally ##
# stores singlespeed analysis plots in separate PLOTS folder in the path_results folder

rm(list = ls())
source("CamtrapSimulation.R", echo=TRUE)

require(ggplot2)
require(ggpubr)

# set which speed parameter to analyse results for
speed_parameter <- 0.2

# set range of seq_dats to analyse
iter <- c(1:45)

# analyse the results and store plots in PLOTS folder:
singlespeed_analyse(speed_parameter, iter)
# --> why does this not run??