## PIPELINE for local use - once paths have been generated by the HPC ##
# runs the simulation using the pre-generated paths from the path_results folder
# stores plot of the first simulation run in the same folder as the paths

setwd("~/Documents/Project/CamtrapSimulation/code")

rm(list = ls())
source("CamtrapSimulation.R", echo=TRUE)

# set which parent folder of paths to analyse of paths to analyse (will always be iter repeats of the same speed)
parentfolder <- paste0("path_results/") 

# set which speed to analyse paths in:
pathfolder <- paste0("sp0.09_29Apr22_1609/")

# # set number of iterations of the path
# iter <- 100 

# set range of paths to run the simulation on:
path_nos <- c(16:40)

# set additional parameters:
species = 0 # currently: 0 = small, 1 = large --> ultimately: want: 1 = small herbivores, 2 = large herbivores, 3 = small carnivores, 4 = large carnivores
r = 9
th = 0.7
twoCTs = FALSE
connectedCTs = FALSE
path_cutby = 1


# run the simulation to save as seq_dats:
generate_seqdats(parentfolder=parentfolder, pathfolder=pathfolder, path_nos=path_nos, species=species, r=r, th=th, twoCTs=twoCTs, connectedCTs=connectedCTs, path_cutby=path_cutby)

# # run the simulation and analyse the results:
# run_and_analyse(parentfolder=parentfolder, pathfolder=pathfolder, iter=iter, species=species, r=r, th=th, twoCTs=twoCTs, connectedCTs=connectedCTs, n_cores=4)

