## PIPELINE for local use - once paths have been generated by the HPC ##
# analyses simulation results across multiple speeds (once simulation has been run on pre-generated paths using pipeline_local_singlespeeds.R)

rm(list = ls())
source("CamtrapSimulation.R", echo=TRUE)

# set which parent folder of paths to analyse of paths to analyse (will always be iter repeats of the same speed)
parentfolder <- paste0("path_results/")

# set the range of speeds to analyse
speeds <- seq(0.05, 0.2, by = 0.005) # TO GO FROM HERE: NEED TO MAKE SURE AVOID ROUNDING ERRORS AND FINISH MAKING FUNCTION

# analyse errors between mean realised speeds and estimated speeds
multi_analyse_est_errors(parentfolder=parentfolder, speeds=speeds)



