## PIPELINE for local use - once paths have been generated by the HPC and seqdats generated locally ##
# stores singlespeed analysis plots in separate PLOTS folder in the path_results folder

setwd("~/Documents/Project/CamtrapSimulation/code")

rm(list = ls())
source("CamtrapSimulation.R", echo=TRUE)

require(ggplot2)
require(ggpubr)

# set which speed parameter to analyse results for
speed_parameter <- 0.95

# set range of seq_dats to analyse
iter <- c(1:50)

# analyse the results and store plots in PLOTS folder:
singlespeed_analyse(speed_parameter, iter)