## PIPELINE for local use - once paths have been generated by the HPC ##
# runs the simulation using the pre-generated paths from the path_results folder
# stores plot of the first simulation run in the same folder as the pathS

setwd("~/Documents/Project/CamtrapSimulation/code")

rm(list = ls())
source("CamtrapSimulation.R", echo=TRUE)

# set range of body masses to run the simulation on:
Mb_range <- c(1,5,10,15,20,25,30,35,40,45,50)

# set range of paths to run the simulation on:
path_nos <- c(1:20)

# set which parent folder of paths to analyse of paths to analyse (will always be iter repeats of the same speed)
parentfolder <- paste0("../results/final_results/paths_uni/")

# set output folder - depends on what you're running
outputfolder <- paste0("../results/final_results/uni_hz_scaling/seq_dats/")


# set additional parameters:
r = 9
th = 0.7
twoCTs = FALSE
connectedCTs = FALSE
path_cutby = 1
scaling=TRUE # whether to scale hz function for detection probability with body mass


# run the simulation to save as seq_dats:
generate_seqdats(parentfolder=parentfolder, outputfolder=outputfolder, Mb_range=Mb_range, path_nos=path_nos, r=r, th=th, twoCTs=twoCTs, connectedCTs=connectedCTs, path_cutby=path_cutby, scaling=scaling)
