## PIPELINE for local use - once paths have been generated by the HPC ##
# runs the simulation using the pre-generated paths from the path_results folder
# stores plots of each simulation run in the same folder as the paths
# stores analysis plots in separate PLOTS folder in the path_results folder

rm(list = ls())
source("CamtrapSimulation.R", echo=TRUE)

# set which parent folder of paths to analyse of paths to analyse (will always be iter repeats of the same speed)
parentfolder <- paste0("path_results/") 

# set which speed to analyse paths in:
pathfolder <- paste0("sp0.05_28Apr22_1724/")

# set number of iterations of the path
iter <- 100 

# set additional parameters:
species = 0 # currently: 0 = small, 1 = large --> ultimately: want: 1 = small herbivores, 2 = large herbivores, 3 = small carnivores, 4 = large carnivores
r = 9
th = 0.7
twoCTs = TRUE
connectedCTs = FALSE


# run the simulation and analyse the results:
run_and_analyse(parentfolder=parentfolder, pathfolder=pathfolder, iter=iter, species=species, r=r, th=th, twoCTs=twoCTs, connectedCTs=connectedCTs, n_cores=4)

