### compile & analyse data on multiple runs of the same simulation for multiple diff speeds ###

require(ggplot2)

setwd("~/Documents/Project/CamtrapSimulation/code/simulation")

setwd("results2/size0_sd1_pTurn0.5_Cor0.9_kTurn2_kCorT_r9_th0.7") # set which one to analyse


## compile data into two dataframes:
# df1: 
# - speed parameter
# - realised speeds
# - observed speeds
# df2: 
# - speed parameter
# - no. of single frames
# - proportion of single frames (= no. single frames / total no. of points captured in all runs of that speed parameter)
# - no. of zero frames
# - proportion of zero frames
# - mean observed sequence length
# - no. of points captured


speed_parameters <- seq(from = 0.05, to = 0.2, by = 0.01)

real <- c()
obs <- c()
speed_lengths <- c()
speed <- c()
singles <- c()
zeros <- c()
points <- c()
#mean_obs_length <- c()
counter <- 0
for (i in speed_parameters){
  counter <- counter + 1
  for (j in 0:9){
    k <- counter + j*16 # run number
    load(paste0("sp", i, "_run", k, ".RData"))
    real <- c(real, seq_dats$realised)
    obs <- c(obs, seq_dats$observed)
    speed_lengths <- c(speed_lengths, length(seq_dats$realised))
    singles <- c(singles, seq_dats$n_singles[1])
    zeros <- c(zeros, seq_dats$n_zeros[1])
    points <- c(points, seq_dats$n_points[1])
    #mean_obs_length <- c(mean_obs_length, seq_dats$mean_obs_length[1])
  }
}

n_singles <- c()
n_zeros <- c()
n_points <- c()
speed_options <- seq(0.05, 0.2, 0.01)
buggynumber <- 0 # DON'T ASK
for (x in 0:15){
  print(0.05 + 0.01*x)
  select <- c(1:10) + 10*x
  # speed_param <- as.numeric(0.05 + 0.01*i)
  speed_param <- speed_options[x+1]
  newspeed <- rep(speed_param, times = sum(speed_lengths[select]))
  speed <- c(speed, newspeed)
  n_singles <- c(n_singles, sum(singles[select]))
  n_zeros <- c(n_zeros, sum(zeros[select]))
  n_points <- c(n_points, sum(points[select]))
  if (x == 1){
    buggynumber <- newspeed[1]
  }
}

# This is the most ludicrous hack. For some godforsaken reason R is deciding to 
# do something weird with the second numer generated by seq.
# Here we save that "number" out, use it as a filtering criterion to replace it
# with the number it should ACTUALLY be. This is a crime against humanity.
speed[which(speed == buggynumber)] <- 0.06
# To test: speed[speed == 0.06] should show more than 0 numbers.

singles_prop <- n_singles/n_points
zeros_prop <- n_zeros/n_points

df1 <- data.frame(speed = speed,
                  real = real,
                  obs = obs)

log_pdf_ratio <- c()
max_obs <- c() # for vertical lines in plot of distributions of observed and realised speeds
max_real <- c() # ditto
for (i in speed_parameters){
  d <- df1[speed==i,]
  o <- d$obs
  o[!is.finite(o)] <- NA
  o <- o[!is.na(o)]
  d_real <- density(d$real)
  d_obs <- density(o)
  real_y <- d_real$y
  obs_y <- d_obs$y
  obs_y[!is.finite(obs_y)] <- NA
  obs_y <- obs_y[!is.na(obs_y)]
  divided <- obs_y/real_y
  divided[!is.finite(divided)] <- NA
  divided <- divided[!is.na(divided)]
  log_pdf_ratio <- c(log_pdf_ratio, log(mean(divided)))
  max_obs <- c(max_obs, d_obs$x[which.max(obs_y)])
  max_real <- c(max_real, d_real$x[which.max(real_y)])
}

df2 <- data.frame(speed_param = speed_parameters,
                  log_pdf_ratio = log_pdf_ratio,
                  n_singles = n_singles,
                  singles_prop = singles_prop,
                  n_zeros = n_zeros,
                  zeros_prop = zeros_prop,
                  #mean_obs_seq_length = mean_obs_length,
                  n_points = n_points)

df3 <- data.frame(speedparameter = rep(df1$speed, times = 2),
                  speed = c(real, obs),
                  obs_real = c(rep("realised", times = length(real)), rep("observed", times = length(obs))))


# trap rate plot ----------------------------------------------------------

trap_rate <- ggplot(df2, aes(x = speed, y = log_pdf_ratio))+
  geom_point()+
  theme_minimal()+
  labs(x = "speed (m/s)",
       y = "log mean error between observed and realised speeds\n(log(mean(observed speed kernel density values / realised speed kernel density values)))")
trap_rate

x <- seq(0,10, by = 0.001)
d_x <- density(x, kernel="epanechnikov")

ggplot()+
  #geom_density(aes(x = d$real), colour = "red")+
  geom_line(aes(x = d_real$x, y = d_real$y), colour = "red")+
  #geom_density(aes(x = o), colour = "blue")+
  geom_line(aes(x = d_obs$x, y = obs_y), colour = "blue")




# look at what's going on with the individual plots:
## PLOT: obs_real
# distribution of observed speeds vs realised speeds for each speed
obs_real <- ggplot(df3, aes(x = speed, colour = obs_real))+
  geom_density()+
  facet_wrap(~ speedparameter, ncol=4)+
  theme_minimal()+
  theme(legend.title = element_blank())+
  scale_colour_manual(values = c("blue", "red"))+
  xlab("speed (m/s)")+
  labs(title = "Distributions of realised and observed speeds")+
  xlim(0,5)+
  geom_vline(data=df3[df3$speedparameter==0.05,], aes(xintercept=max_real[1]), colour="red")+
  geom_vline(data=df3[df3$speedparameter==0.05,], aes(xintercept=max_obs[1]), colour="blue")+
  geom_vline(data=df3[df3$speedparameter==0.06,], aes(xintercept=max_real[2]), colour="red")+
  geom_vline(data=df3[df3$speedparameter==0.06,], aes(xintercept=max_obs[2]), colour="blue")
  # geom_vline(data=df3[df3$speedparameter==0.07,], aes(xintercept=max_real[3]), colour="red")+
  # geom_vline(data=df3[df3$speedparameter==0.07,], aes(xintercept=max_obs[3]), colour="blue")+
  # geom_vline(data=df3[df3$speedparameter==0.08,], aes(xintercept=max_real[4]), colour="red")+
  # geom_vline(data=df3[df3$speedparameter==0.08,], aes(xintercept=max_obs[4]), colour="blue")+
  # geom_vline(data=df3[df3$speedparameter==0.09,], aes(xintercept=max_real[5]), colour="red")+
  # geom_vline(data=df3[df3$speedparameter==0.09,], aes(xintercept=max_obs[5]), colour="blue")+
  # geom_vline(data=df3[df3$speedparameter==0.1,], aes(xintercept=max_real[6]), colour="red")+
  # geom_vline(data=df3[df3$speedparameter==0.1,], aes(xintercept=max_obs[6]), colour="blue")+
  # geom_vline(data=df3[df3$speedparameter==0.11,], aes(xintercept=max_real[7]), colour="red")+
  # geom_vline(data=df3[df3$speedparameter==0.11,], aes(xintercept=max_obs[7]), colour="blue")+
  # geom_vline(data=df3[df3$speedparameter==0.12,], aes(xintercept=max_real[8]), colour="red")+
  # geom_vline(data=df3[df3$speedparameter==0.12,], aes(xintercept=max_obs[8]), colour="blue")+
  # geom_vline(data=df3[df3$speedparameter==0.13,], aes(xintercept=max_real[9]), colour="red")+
  # geom_vline(data=df3[df3$speedparameter==0.13,], aes(xintercept=max_obs[9]), colour="blue")+
  # geom_vline(data=df3[df3$speedparameter==0.14,], aes(xintercept=max_real[10]), colour="red")+
  # geom_vline(data=df3[df3$speedparameter==0.14,], aes(xintercept=max_obs[10]), colour="blue")+
  # geom_vline(data=df3[df3$speedparameter==0.15,], aes(xintercept=max_real[11]), colour="red")+
  # geom_vline(data=df3[df3$speedparameter==0.15,], aes(xintercept=max_obs[11]), colour="blue")+
  # geom_vline(data=df3[df3$speedparameter==0.16,], aes(xintercept=max_real[12]), colour="red")+
  # geom_vline(data=df3[df3$speedparameter==0.16,], aes(xintercept=max_obs[12]), colour="blue")+
  # geom_vline(data=df3[df3$speedparameter==0.17,], aes(xintercept=max_real[13]), colour="red")+
  # geom_vline(data=df3[df3$speedparameter==0.17,], aes(xintercept=max_obs[13]), colour="blue")+
  # geom_vline(data=df3[df3$speedparameter==0.18,], aes(xintercept=max_real[14]), colour="red")+
  # geom_vline(data=df3[df3$speedparameter==0.18,], aes(xintercept=max_obs[14]), colour="blue")+
  # geom_vline(data=df3[df3$speedparameter==0.19,], aes(xintercept=max_real[15]), colour="red")+
  # geom_vline(data=df3[df3$speedparameter==0.19,], aes(xintercept=max_obs[15]), colour="blue")+
  # geom_vline(data=df3[df3$speedparameter==0.2,], aes(xintercept=max_real[16]), colour="red")+
  # geom_vline(data=df3[df3$speedparameter==0.2,], aes(xintercept=max_obs[16]), colour="blue")
obs_real






# plotting biases ---------------------------------------------------------

## PLOT: obs_real.png
# comparisons of observed vs realised speeds
obs_real_df <- data.frame(speed = c(real, obs),
                          obs_real = c(rep("realised", length(real)), rep("observed", length(obs))))
obs_real_plot <- ggplot(obs_real_df, aes(x = speed, colour = obs_real))+
  geom_density()+
  theme_minimal()+
  theme(legend.title = element_blank(),
        legend.position = "bottom")+
  scale_colour_manual(values = c("blue", "red"))+
  xlab("speed (m/s)")+
  labs(title = "Distributions of realised and observed speeds")+
  geom_vline(xintercept = density(real)$x[which.max(density(real)$y)], colour = "red")+
  geom_vline(xintercept = density(obs)$x[which.max(density(obs)$y)], colour = "blue")
obs_real_plot

obs_real_error_df <- data.frame(error = obs_real_error)

obs_real_error_plot <- ggplot(obs_real_error_df, aes(x = error))+
  geom_density(size = 1)+
  theme_minimal()+
  labs(x = "error (m/s)",
       title = "Distribution of errors between observed and realised speeds")+
  geom_vline(xintercept = 0, linetype = "dashed")+
  geom_text(x = -1, y = 0.1, label = "obs > real", size = 3)+
  geom_text(x = 1, y = 0.1, label = "real > obs", size = 3)
obs_real_error_plot

png(file="obs_real.png",
    width=700, height=600)
obs_real_arranged <- ggarrange(obs_real_plot, obs_real_error_plot, nrow = 2)
annotate_figure(obs_real_arranged, top = text_grob(paste("mean realised speed = ", round_dp(mean(real), 3), "m/s, number of observed speeds = ", length(obs), "\nsingle frame prop = ", signif(singles_prop, 3), ", zero frame prop = ", signif(zeros_prop, 3), "\nmean observed sequence length = ", mean(obs_lengths), sep = ""), 
                                                   face = "bold", size = 14))
dev.off()


# calculate estimated speeds - using hmean and SBMs #####

harmonic <- (hmean(obs))[1] # harmonic mean estimate
obs_df <- data.frame(speed = obs)
mods <- sbm3(speed~1, obs_df) # fit all the models
lnorm <- predict.sbm(mods[[1]]$lnorm)[1,1] # lnorm speed estimate
gamma <- predict.sbm(mods[[1]]$gamma)[1,1] # gamma speed estimate
weibull <- predict.sbm(mods[[1]]$weibull)[1,1] # weibull speed estimate

# plot
real_df <- data.frame(real = real)
estimates_plot <- ggplot(real_df, aes(x = real))+
  geom_density()+
  theme_minimal()+
  labs(x = "realised speed (m/s)",
       title = "Estimates of mean realised speed overlaying the distribution of realised speeds")+
  theme(legend.position = "bottom")+
  geom_vline(aes(xintercept = density(real)$x[which.max(density(real)$y)], colour = "raw"))+
  geom_vline(aes(xintercept = harmonic, colour = "harmonic"), show.legend = TRUE)+
  geom_vline(aes(xintercept = lnorm, colour = "lnorm"), show.legend = TRUE)+
  geom_vline(aes(xintercept = gamma, colour = "gamma"))+
  geom_vline(aes(xintercept = weibull, colour = "weibull"))+
  scale_color_manual(name = "type of mean", values = c(raw = "black", harmonic = "orange", lnorm = "red", gamma = "blue", weibull = "green"))
estimates_plot

png(file="estimates.png",
    width=700, height=600)
estimates_plot
dev.off()

# errors between estimates and realised speeds
hmean_error <- harmonic - mean(real)
lnorm_error <- lnorm - mean(real)
gamma_error <- gamma - mean(real)
weibull_error <- weibull - mean(real)





