## PIPELINE for local use - once paths have been generated by the HPC ##
# makes a list of all the paths ready to send back to the cluster to run the simulation

rm(list = ls())
source("CamtrapSimulation.R", echo=TRUE)

# set which paths to analyse (will always be iter repeats of the same speed)
folder <- "path_results/sp0.18_30Apr22_1913" 

# set number of iterations of the path
iter <- 100

# make list of all 100 paths to be sent to run simulation on in parallel on cluster
path_list(folder, iter)
# --> then send this to cluster

# next local script to run: pipeline_local2.R