## PIPELINE for local use - once paths have been generated by the HPC ##
# runs the simulation using the pre-generated paths from the path_results folder
# stores plots of each simulation run in the same folder as the paths
# stores analysis plots in separate PLOTS folder in the path_results folder





practice_fun <- function(){
  l <- list(days = c(10,8,8),
            months = c(9,0,4,5))
  return(l)
}

prac <- practice_fun()









rm(list = ls())
source("CamtrapSimulation.R", echo=TRUE)

# set which paths to analyse (will always be iter repeats of the same speed)
which_path <- paste0("path_results/26Apr22_1645_iter", i, ".RData") 

# set number of iterations of the path
iter <- 100 

# set additional parameters:
species = 0 # currently: 0 = small, 1 = large --> ultimately: want: 1 = small herbivores, 2 = large herbivores, 3 = small carnivores, 4 = large carnivores
x = 20
y = 10
r = 9
th = 0.7
plot_path = TRUE
twoCTs = FALSE


## run_and_analyse
# runs the simulation on pre-generated paths in the path_results folder (iter repeats of the same path)
# if plot_path = TRUE, plots the simulation plot for each run and stores in the same folder as the paths
# plots analysis plots and stores them in separate path_results/PLOTS folder
# INPUTS:
# which_path = which set of paths to analyse (each set contains iter reps of the same speed & parameters)
# species = currently: 0 = small, 1 = large --> ultimately: want: 1 = small herbivores, 2 = large herbivores, 3 = small carnivores, 4 = large carnivores
# x,y = CT coords
# r = radius of CT detection zone
# th = angle of CT detection zone
# plot_path = logical - whether to plot the simulation for each iteration
# twoCTs = logical - whether to set up two CTs next to each other
# n_cores = number of cores of your laptop - to parallelise sapply
# OUTPUTs:
# simulation plots for each iteration if plot_path = TRUE - saved into the same folder as the paths
# analysis plots - saved into the PLOTS folder
run_and_analyse <- function(which_path, iter, species, x, y, r, th, plot_path, twoCTs, n_cores=4){
  ## run the simulation on each of the paths
  paths <- c() # make a vector of the paths so that can sapply the simulation to them
  for (i in 1:iter){
    paths <- c(paths, load(which_path))
  }
  seq_dats <- mcsapply(paths, run_simulation, mc.cores = n_cores, species=species, x=x, y=y, r=r, th=th, plot_path=plot_path, twoCTs=twoCTs)
  
  ## for each iteration: work out estimated speeds and the error between mean realised and each estimated speed
  estimates <- mcsapply(seq_dats, estimates_calc, mc.cores = n_cores) 
  # concatenate results into a dataframe:
  mean_reals <- c()
  hmeans <- c()
  lnorms <- c()
  gammas <- c()
  weibulls <- c()
  lnorm_errors <- c()
  gamma_errors <- c()
  weibull_errors <- c()
  for (i in 1:length(estimates)){
    e <- estimates[i] # might need to change this depending on format of estimates
    mean_reals <- c(mean_reals, e$mean_real)
    hmeans <- c(hmeans, e$hmean)
    lnorms <- c(lnorms, e$lnorm)
    gammas <- c(gammas, e$gamma)
    weibulls <- c(weibulls, e$weibull)
    lnorm_errors <- c(lnorm_errors, e$lnorm_error)
    gamma_errors <- c(gamma_errors, e$gamma_error)
    weibull_errors <- c(weibull_errors, e$weibull_error)
  }
  estimates_df <- data.frame(iter = c(1:iter), mean_real=mean_reals, hmean=hmeans, lnorm=lnorms, gamma=gammas, weibull=weibulls, hmean_error=hmean_errors, lnorm_error=lnorm_errors, gamma_error=gamma_errors, weibull_error=weibull_errors)
  
  # make and store realised vs observed plot
  
  ## obs_meanreal_error_calc - BUT: INSTEAD MAYBE TRY TO GET THIS FROM ABOVE FUNCTION
  # work out error between each observed speed and the mean realised speed for that iteration
  # INPUTS:
  # seq_dats: list of simulation run outputs (one set of outputs per iteration)
  # number of iterations
  # OUTPUT:
  # vector of errors between observed and mean realised speeds
  obs_meanreal_error_calc <- function(seq_dats, iter){
    
    
    
    
    return(errors)
  }
  obs_meanreal_errors <- obs_meanreal_error_calc(seq_dats, iter)
  
  
  
  # make and store mean realised vs estimates plot:

  png(file="estimates_errors.png",
      width=700, height=600)
  # estimates_plot
  dev.off()
  
  
  
  
  
  
  
  real <- c()
  obs <- c()
  obs_lengths <- c()
  n_singles <- 0
  n_zeros <- 0
  n_points <- 0
  for (i in c(1:10)){
    load(paste0("run", i, ".RData"))
    real <- c(real, seq_dats$realised)
    o <- seq_dats$observed
    o[!is.finite(o)] <- NA
    o <- o[!is.na(o)]
    obs <- c(obs, o)
    obs_lengths <- c(obs_lengths, seq_dats$obs_lengths)
    n_singles <- n_singles + seq_dats$n_singles[1]
    n_zeros <- n_zeros + seq_dats$n_zeros[1]
    n_points <- n_points + seq_dats$n_points[1]
  }
  
  singles_prop <- n_singles/n_points
  zeros_prop <- n_zeros/n_points
  
  obs_real_error <- c()
  for (i in 1:length(obs)){
    e <- obs[i] - mean(real)
    obs_real_error <- c(obs_real_error, e)
  }
  
  
  
  
  # compile together data from these repeats
  
  
  
  
  
  
  
  # make & store plots:
  png(file= paste0(filename, ".png"),
      width=700, height=650)
  seq_dats <- seq_dat(path=path, species=species, x=x, y=y, r=r, th=th, plot_path = plot_path, twoCTs = twoCTs)
  dev.off()
  
  
  
  
}







