## PIPELINE for local use - once paths have been generated by the HPC AND the simulation run on the HPC too ##
# analyses the simulation run using the pre-generated paths
# stores plots of each simulation run in the same folder as the paths
# stores analysis plots in separate PLOTS folder in the path_results folder

## TO CHANGE ONCE HAVE RESULTS


rm(list = ls())
source("CamtrapSimulation.R", echo=TRUE)

# set which paths to analyse (will always be iter repeats of the same speed)
folder <- "path_results/sp0.05_28Apr22_1724" 

# set number of iterations of the path
iter <- 100 

# set additional parameters:
species = 0 # currently: 0 = small, 1 = large --> ultimately: want: 1 = small herbivores, 2 = large herbivores, 3 = small carnivores, 4 = large carnivores
x = 20
y = 10
r = 9
th = 0.7
plot_path = TRUE
twoCTs = FALSE

n_cores = 4

# # run the simulation and analyse the results:
# run_and_analyse(folder, iter, species, x, y, r, th, plot_path, twoCTs, n_cores=4)
# --> TOO SLOW - INSTEAD SEND SEQ_DATS TO HPC

# make list of all 100 paths to be sent to run simulation on in parallel on cluster
path_list(folder, iter)
# --> then send this to cluster

# next script to run: pipeline_local2.R