## PIPELINE for local use - once path has been generated by the HPC ##

rm(list = ls())

source("CamtrapSimulation.R", echo=TRUE)

# set speed parameters
speed_parameter <- c(0.05)

# set parameters
# path: 
species = 0 # currently: 0 = small, 1 = large --> ultimately: want: 1 = small herbivores, 2 = large herbivores, 3 = small carnivores, 4 = large carnivores
xlim = c(0,40)
# dz dimensions:
x = 20
y = 10
r = 9
th = 0.7
# other:
plot_path = TRUE
twoCTs = FALSE

filename <- paste0(speed_parameter, "_y", y, "_r", r, "_th", th, "_run", iter) # to change - and make sure speed_parameter is in here if doing multiple speeds

png(file= paste0(filename, ".png"),
    width=700, height=650)
seq_dats <- seq_dat(path=path, species=species, x=x, y=y, r=r, th=th, plot_path = plot_path, twoCTs = twoCTs)
dev.off()

save(seq_dats, file = paste0(filename, ".RData"))
