## PIPELINE for local use - once paths have been generated by the HPC ##
# runs the simulation using the pre-generated paths from the path_results folder
# stores plots of each simulation run in the same folder as the paths
# stores analysis plots in separate PLOTS folder in the path_results folder

rm(list = ls())
source("CamtrapSimulation.R", echo=TRUE)

# set which paths to analyse (will always be iter repeats of the same speed)
which_path <- paste0("path_results/26Apr22_1645_iter", i, ".RData") 

# set number of iterations of the path
iter <- 100 

# set additional parameters:
species = 0 # currently: 0 = small, 1 = large --> ultimately: want: 1 = small herbivores, 2 = large herbivores, 3 = small carnivores, 4 = large carnivores
x = 20
y = 10
r = 9
th = 0.7
plot_path = TRUE
twoCTs = FALSE


# run the simulation and analyse the results:
run_and_analyse(which_path, iter, species, x, y, r, th, plot_path, twoCTs, n_cores=4)

